name: build-and-test-plugin-with-irods-packages

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │  ┌───────────── day of the month (1 - 31)
    #        │  │  │  ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        *  *  *  *  *
    - cron: "0  7  *  *  1" # Run at 7:00am UTC every Monday morning.

defaults:
  run:
    shell: bash

jobs:
  build_and_test_plugin_with_prerelease_packages_using_default_matrix:
    uses: irods/irods_reusable_github_workflows/.github/workflows/build-and-test-plugin-with-irods-packages-matrix.yml@main
